<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-deep-learning/blob/main/1.1.%20Perceptron(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
)


### Prepare input data

In [3]:
lstX = [[1,2,3], [4,5,6],[7,8,9]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 
 torch.Size([3, 3])


In [4]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[ 0.3929, -0.5034,  0.4806]])
0.bias tensor([-0.1351])


1. Use Pytorch matrix multiplcation: tensor1.mm(tensor2) to calculate answer

In [5]:
W0 = MyNet[0].weight
print(W0, W0.shape)

Parameter containing:
tensor([[ 0.3929, -0.5034,  0.4806]], requires_grad=True) torch.Size([1, 3])


In [6]:
# transpose of W0
W0t = torch.transpose(W0, 1, 0)
print(W0t, W0t.shape)

tensor([[ 0.3929],
        [-0.5034],
        [ 0.4806]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


In [7]:
tensorX.mm(W0t)

tensor([[0.8278],
        [1.9381],
        [3.0484]], grad_fn=<MmBackward0>)

In [8]:
tensorX.mm(W0t)+MyNet[0].bias

tensor([[0.6927],
        [1.8030],
        [2.9133]], grad_fn=<AddBackward0>)

In [9]:
relu = nn.ReLU()

In [10]:
relu(tensorX.mm(W0t)+MyNet[0].bias)

tensor([[0.6927],
        [1.8030],
        [2.9133]], grad_fn=<ReluBackward0>)

2. Using Excel to verify