<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-deep-learning/blob/main/1.1.%20Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
)


In [3]:
# test Relu activatio function
relu = nn.ReLU()
x = torch.FloatTensor([-0.23, -56.7, 34])
relu(x)

tensor([ 0.,  0., 34.])

### Prepare input data

In [4]:
lstX = [[1,2,3]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[1., 2., 3.]]) 
 torch.Size([1, 3])


In [5]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[0.0633, 0.2253, 0.2754]])
0.bias tensor([0.4866])


1. Use Pytorch matrix multiplcation: tensor1.mm(tensor2) to calculate answer

$W0=(w1, w2, w3)$

In [6]:
W0 = MyNet[0].weight
print(W0, W0.shape)

Parameter containing:
tensor([[0.0633, 0.2253, 0.2754]], requires_grad=True) torch.Size([1, 3])


$W0T=(w1, w2, w3)T$

In [7]:
# transpose of W0
W0t = torch.transpose(W0, 1, 0)
print(W0t, W0t.shape)

tensor([[0.0633],
        [0.2253],
        [0.2754]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


$x*W0T=(x1, x2, x3)(w1, w2, w3)T$

In [8]:
tensorX.mm(W0t)

tensor([[1.3401]], grad_fn=<MmBackward0>)

$x*W0T + b=(x1, x2, x3)(w1, w2, w3)T+b$

In [9]:
tensorX.mm(W0t)+MyNet[0].bias

tensor([[1.8267]], grad_fn=<AddBackward0>)

$Relu(x*W0T + b)=Relu((x1, x2, x3)(w1, w2, w3)T+b)$

In [10]:
relu(tensorX.mm(W0t)+MyNet[0].bias)

tensor([[1.8267]], grad_fn=<ReluBackward0>)

2. Using Excel to verify

$Relu (w1*x1 + w2*x2 + w3*x3 + b)$