<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-Colab/blob/main/1.1.%20Perceptron(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
)


### Prepare input data

In [3]:
lstX = [[1,2,3], [4,5,6],[7,8,9]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 
 torch.Size([3, 3])


In [4]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[-0.2659, -0.1028,  0.4902]])
0.bias tensor([-0.2821])


1. Use Pytorch matrix multiplcation: tensor1.mm(tensor2) to calculate answer

In [5]:
W0 = MyNet[0].weight
print(W0, W0.shape)

Parameter containing:
tensor([[-0.2659, -0.1028,  0.4902]], requires_grad=True) torch.Size([1, 3])


In [6]:
# transpose of W0
W0t = torch.transpose(W0, 1, 0)
print(W0t, W0t.shape)

tensor([[-0.2659],
        [-0.1028],
        [ 0.4902]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


In [7]:
tensorX.mm(W0t)

tensor([[0.9990],
        [1.3635],
        [1.7279]], grad_fn=<MmBackward>)

In [8]:
tensorX.mm(W0t)+MyNet[0].bias

tensor([[0.7169],
        [1.0813],
        [1.4458]], grad_fn=<AddBackward0>)

In [10]:
relu = nn.ReLU()

In [11]:
relu(tensorX.mm(W0t)+MyNet[0].bias)

tensor([[0.7169],
        [1.0813],
        [1.4458]], grad_fn=<ReluBackward0>)

2. Using Excel to verify