<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-Colab/blob/main/1.1.%20Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# Examine how the neuron perceive data (takes input data and generate output)

In [2]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
)


# Prepare input data

In [3]:
lstX = [[1,2,3]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[1., 2., 3.]]) 
 torch.Size([1, 3])


In [4]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[ 0.0380, -0.4209, -0.2855]])
0.bias tensor([0.4196])


In [5]:
W0 = MyNet[0].weight
print(W0, W0.shape)

Parameter containing:
tensor([[ 0.0380, -0.4209, -0.2855]], requires_grad=True) torch.Size([1, 3])


In [6]:
W0t = torch.transpose(W0, 1, 0)
print(W0t, W0t.shape)

tensor([[ 0.0380],
        [-0.4209],
        [-0.2855]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


In [7]:
tensorX.mm(W0t)

tensor([[-1.6602]], grad_fn=<MmBackward>)

In [8]:
tensorX.mm(W0t)+MyNet[0].bias

tensor([[-1.2406]], grad_fn=<AddBackward0>)

In [10]:
# test Relu activatio function
relu = nn.ReLU()
x = torch.FloatTensor([-0.23, -56.7, 34])
relu(x)

tensor([ 0.,  0., 34.])

In [12]:
relu(tensorX.mm(W0t)+MyNet[0].bias)

tensor([[0.]], grad_fn=<ReluBackward0>)