<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-Colab/blob/main/1.1.%20Forward%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# Build NN

In [ ]:
MyNet = nn.Sequential(
  nn.Linear(2, 3),
  nn.Linear(3, 2),
  nn.Linear(2, 1)
)
print(MyNet)

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [ ]:
for param in MyNet.parameters():
    if param.requires_grad:
        print(param.data)

tensor([[ 0.4727, -0.5188],
        [-0.5681, -0.6032],
        [-0.0252, -0.3011]])
tensor([-0.6986, -0.6602, -0.4860])
tensor([[-0.5549,  0.2550,  0.4584],
        [ 0.2930,  0.0849, -0.3146]])
tensor([0.1677, 0.0736])
tensor([[ 0.4106, -0.3618]])
tensor([-0.2270])


# Prepare input data

In [ ]:
lstX = [[1, 2], [2, 3], [10, 5]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[ 1.,  2.],
        [ 2.,  3.],
        [10.,  5.]]) 
 torch.Size([3, 2])


In [ ]:
lstY = [[7], [12], [40]]  # y=3x1+2x2
tensorY = torch.FloatTensor(lstY)
print(tensorY, '\n', tensorY.shape)

tensor([[ 7.],
        [12.],
        [40.]]) 
 torch.Size([3, 1])


# Forward propagation

###Hidden layer 1: n3, n4, n5 

In [ ]:
W1 = MyNet[0].weight
b1 = MyNet[0].bias   
print(W1, W1.shape, b1)

Parameter containing:
tensor([[ 0.4727, -0.5188],
        [-0.5681, -0.6032],
        [-0.0252, -0.3011]], requires_grad=True) torch.Size([3, 2]) Parameter containing:
tensor([-0.6986, -0.6602, -0.4860], requires_grad=True)


In [ ]:
#Calculate n3, n4, n5
HiddenLayer1 = MyNet[0](tensorX)  
print(HiddenLayer1)

tensor([[-1.2635, -2.4348, -1.1135],
        [-1.3097, -3.6061, -1.4398],
        [ 1.4340, -9.3577, -2.2441]], grad_fn=<AddmmBackward>)


In [ ]:
#Calculate n3, n4, n5 using Pytorch matrix operation
HiddenLayer1 = tensorX.mm(torch.transpose(W1, 1, 0)) + b1
print(HiddenLayer1)

tensor([[-1.2635, -2.4348, -1.1135],
        [-1.3097, -3.6061, -1.4398],
        [ 1.4340, -9.3577, -2.2441]], grad_fn=<AddBackward0>)


###Hidden layer 2: n6, n7

In [ ]:
#Calculate n6, n7
HiddenLayer2 = MyNet[1](HiddenLayer1)
print(HiddenLayer2)

tensor([[-0.2625, -0.1530],
        [-0.6852, -0.1632],
        [-4.0429,  0.4054]], grad_fn=<AddmmBackward>)


In [ ]:
#Calculate n6, n7 using PyTorch matrix operation
W2 = MyNet[1].weight
b2 = MyNet[1].bias  
HiddenLayer2 = HiddenLayer1.mm(torch.transpose(W2, 1, 0)) +b2
print(HiddenLayer2)

tensor([[-0.2625, -0.1530],
        [-0.6852, -0.1632],
        [-4.0429,  0.4054]], grad_fn=<AddBackward0>)


###Output layer

In [ ]:
#Calculate y
tensorY1= MyNet[2](HiddenLayer2)
print(tensorY1)

tensor([[-0.2795],
        [-0.4493],
        [-2.0335]], grad_fn=<AddmmBackward>)


In [ ]:
#Calculate y
W3 = MyNet[2].weight
b3 = MyNet[2].bias  
tensorY1 = HiddenLayer2.mm(torch.transpose(W3, 1, 0)) +b3
print(tensorY1)

tensor([[-0.2795],
        [-0.4493],
        [-2.0335]], grad_fn=<AddBackward0>)


#y=NN(x)

In [ ]:
#Directly calculate y
tensorY= MyNet(tensorX)
print(tensorY)

tensor([[-0.2795],
        [-0.4493],
        [-2.0335]], grad_fn=<AddmmBackward>)
