<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-Colab/blob/main/1.1.%20Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

# Input -> One neuron -> output

In [8]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
  nn.Linear(1, 1)
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
  (2): Linear(in_features=1, out_features=1, bias=True)
)


# Prepare input data

In [29]:
lstX = [[1,2,3]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[1., 2., 3.]]) 
 torch.Size([1, 3])


In [30]:
lstY = [22]  # y=3x1+2x2+5x3
tensorY = torch.FloatTensor(lstY)
print(tensorY, '\n', tensorY.shape)

tensor([22.]) 
 torch.Size([1])


# Examine how the neuron perceive (takes input data and generate output)

In [31]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[-0.3854,  0.1630,  0.3004]])
0.bias tensor([0.5214])
2.weight tensor([[-0.7900]])
2.bias tensor([0.4422])


In [32]:
W1 = MyNet[0].weight
print(W1, W1.shape)

Parameter containing:
tensor([[-0.3854,  0.1630,  0.3004]], requires_grad=True) torch.Size([1, 3])


In [33]:
W1t = torch.transpose(W1, 1, 0)
print(W1t, W1t.shape)

tensor([[-0.3854],
        [ 0.1630],
        [ 0.3004]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


In [35]:
tensorX.mm(W1t)

tensor([[0.8416]], grad_fn=<MmBackward>)

In [36]:
tensorX.mm(W1t)+MyNet[0].bias

tensor([[1.3630]], grad_fn=<AddBackward0>)

In [46]:
x = torch.FloatTensor([[-0.23]])
nn.ReLU(x)

ReLU(inplace=True)

In [51]:
m = nn.ReLU()
x = torch.FloatTensor([-0.23, -56.7, 34])
m(x)

tensor([ 0.,  0., 34.])

In [52]:
m(tensorX.mm(W1t)+MyNet[0].bias)

tensor([[1.3630]], grad_fn=<ReluBackward0>)