<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-Colab/blob/main/1.2%20MLP%20forward%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

### Build MLP

In [2]:
MyNet = nn.Sequential(
  nn.Linear(2, 3),
  nn.Linear(3, 2),
  nn.Linear(2, 1)
)
print(MyNet)

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [3]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[ 0.6779, -0.0679],
        [ 0.2236,  0.2271],
        [-0.3528, -0.5507]])
0.bias tensor([-0.0836, -0.3327, -0.1703])
1.weight tensor([[-0.1510, -0.3248, -0.2973],
        [-0.5697,  0.0443, -0.0558]])
1.bias tensor([ 0.4943, -0.0836])
2.weight tensor([[-0.1826, -0.6647]])
2.bias tensor([0.4295])


### Prepare input data

In [4]:
lstX = [[1, 2], [2, 3], [10, 5]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[ 1.,  2.],
        [ 2.,  3.],
        [10.,  5.]]) 
 torch.Size([3, 2])


### Forward propagation

In [5]:
W0 = MyNet[0].weight
b0 = MyNet[0].bias   
print(W0, W0.shape, b0)

Parameter containing:
tensor([[ 0.6779, -0.0679],
        [ 0.2236,  0.2271],
        [-0.3528, -0.5507]], requires_grad=True) torch.Size([3, 2]) Parameter containing:
tensor([-0.0836, -0.3327, -0.1703], requires_grad=True)


In [6]:
#Calculate n3, n4, n5 using Pytorch matrix operation
Layer1_1 = tensorX.mm(torch.transpose(W0, 1, 0)) + b0
print(Layer1_1)

tensor([[ 0.4585,  0.3450, -1.6244],
        [ 1.0685,  0.7957, -2.5278],
        [ 6.3557,  3.0385, -6.4514]], grad_fn=<AddBackward0>)


In [7]:
#Verify
Layer1 = MyNet[0](tensorX)  
print(Layer1)

tensor([[ 0.4585,  0.3450, -1.6244],
        [ 1.0685,  0.7957, -2.5278],
        [ 6.3557,  3.0385, -6.4514]], grad_fn=<AddmmBackward>)


###Hidden layer 2: n6, n7

In [8]:
#Calculate n6, n7 using PyTorch matrix operation
W1 = MyNet[1].weight
b1 = MyNet[1].bias  
Layer2_1 = Layer1.mm(torch.transpose(W1, 1, 0)) +b1
print(Layer2_1)

tensor([[ 0.7959, -0.2388],
        [ 0.8260, -0.5158],
        [ 0.4656, -3.2092]], grad_fn=<AddBackward0>)


In [9]:
#verify 
Layer2 = MyNet[1](Layer1)
print(Layer2)

tensor([[ 0.7959, -0.2388],
        [ 0.8260, -0.5158],
        [ 0.4656, -3.2092]], grad_fn=<AddmmBackward>)


###Output layer

In [10]:
#Calculate y by matrix operation
W2 = MyNet[2].weight
b2 = MyNet[2].bias  
tensorY_1 = Layer2.mm(torch.transpose(W2, 1, 0)) +b2
print(tensorY_1)

tensor([[0.4429],
        [0.6216],
        [2.4779]], grad_fn=<AddBackward0>)


In [11]:
#verify 
tensorY= MyNet[2](Layer2)
print(tensorY)

tensor([[0.4429],
        [0.6216],
        [2.4779]], grad_fn=<AddmmBackward>)


### y=NN(x) in one step

In [12]:
#Directly calculate y
tensorY= MyNet(tensorX)
print(tensorY)

tensor([[0.4429],
        [0.6216],
        [2.4779]], grad_fn=<AddmmBackward>)
