<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-Colab/blob/main/1.2%20MLP%20forward%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# Build NN

In [2]:
MyNet = nn.Sequential(
  nn.Linear(2, 3),
  nn.Linear(3, 2),
  nn.Linear(2, 1)
)
print(MyNet)

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [3]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[ 0.0063, -0.6690],
        [-0.6892, -0.5403],
        [ 0.5074, -0.6063]])
0.bias tensor([0.2862, 0.5153, 0.3472])
1.weight tensor([[ 0.4099, -0.2223,  0.4006],
        [ 0.4599, -0.2916, -0.4060]])
1.bias tensor([0.5159, 0.2593])
2.weight tensor([[ 0.3448, -0.2068]])
2.bias tensor([-0.2380])


# Prepare input data

In [4]:
lstX = [[1, 2], [2, 3], [10, 5]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[ 1.,  2.],
        [ 2.,  3.],
        [10.,  5.]]) 
 torch.Size([3, 2])


In [5]:
lstY = [[7], [12], [40]]  # y=3x1+2x2
tensorY_hat = torch.FloatTensor(lstY)
print(tensorY_hat, '\n', tensorY_hat.shape)

tensor([[ 7.],
        [12.],
        [40.]]) 
 torch.Size([3, 1])


# Forward propagation

###Hidden layer 1: n3, n4, n5 

In [6]:
W0 = MyNet[0].weight
b0 = MyNet[0].bias   
print(W0, W0.shape, b0)

Parameter containing:
tensor([[ 0.0063, -0.6690],
        [-0.6892, -0.5403],
        [ 0.5074, -0.6063]], requires_grad=True) torch.Size([3, 2]) Parameter containing:
tensor([0.2862, 0.5153, 0.3472], requires_grad=True)


In [8]:
#Calculate n3, n4, n5
Layer1 = MyNet[0](tensorX)  
print(Layer1)

tensor([[-1.0455, -1.2545, -0.3579],
        [-1.7082, -2.4840, -0.4568],
        [-2.9958, -9.0781,  2.3898]], grad_fn=<AddmmBackward>)


In [9]:
#Calculate n3, n4, n5 using Pytorch matrix operation
Layer1_1 = tensorX.mm(torch.transpose(W0, 1, 0)) + b0
print(Layer1_1)

tensor([[-1.0455, -1.2545, -0.3579],
        [-1.7082, -2.4840, -0.4568],
        [-2.9958, -9.0781,  2.3898]], grad_fn=<AddBackward0>)


###Hidden layer 2: n6, n7

In [10]:
#Calculate n6, n7
Layer2 = MyNet[1](Layer1)
print(Layer2)

tensor([[0.2228, 0.2897],
        [0.1848, 0.3836],
        [2.2630, 0.5587]], grad_fn=<AddmmBackward>)


In [11]:
#Calculate n6, n7 using PyTorch matrix operation
W1 = MyNet[1].weight
b1 = MyNet[1].bias  
Layer2_1 = Layer1.mm(torch.transpose(W1, 1, 0)) +b1
print(Layer2_1)

tensor([[0.2228, 0.2897],
        [0.1848, 0.3836],
        [2.2630, 0.5587]], grad_fn=<AddBackward0>)


###Output layer

In [12]:
#Calculate y
tensorY= MyNet[2](Layer2)
print(tensorY)

tensor([[-0.2211],
        [-0.2537],
        [ 0.4266]], grad_fn=<AddmmBackward>)


In [13]:
#Calculate y by matrix operation
W2 = MyNet[2].weight
b2 = MyNet[2].bias  
tensorY_1 = Layer2.mm(torch.transpose(W2, 1, 0)) +b2
print(tensorY_1)

tensor([[-0.2211],
        [-0.2537],
        [ 0.4266]], grad_fn=<AddBackward0>)


#calculate y=NN(x) in one step

In [14]:
#Directly calculate y
tensorY= MyNet(tensorX)
print(tensorY)

tensor([[-0.2211],
        [-0.2537],
        [ 0.4266]], grad_fn=<AddmmBackward>)
