<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-deep-learning/blob/main/1.2%20MLP%20forward%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
MyNet = nn.Sequential(
  nn.Linear(2, 3),
  nn.Linear(3, 2),
  nn.Linear(2, 1)
)
print(MyNet)

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [3]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[-0.4092, -0.0522],
        [-0.3581, -0.5720],
        [ 0.5493,  0.5701]])
0.bias tensor([ 0.6820,  0.5795, -0.1028])
1.weight tensor([[ 0.1976, -0.1876, -0.2304],
        [ 0.3506, -0.5113, -0.3481]])
1.bias tensor([ 0.2052, -0.0102])
2.weight tensor([[0.6875, 0.1049]])
2.bias tensor([0.1040])


### Prepare input data

In [4]:
lstX = [[1, 2], [2, 3], [10, 5]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[ 1.,  2.],
        [ 2.,  3.],
        [10.,  5.]]) 
 torch.Size([3, 2])


### Forward propagation

In [5]:
W0 = MyNet[0].weight
b0 = MyNet[0].bias   
print(W0, W0.shape, b0)

Parameter containing:
tensor([[-0.4092, -0.0522],
        [-0.3581, -0.5720],
        [ 0.5493,  0.5701]], requires_grad=True) torch.Size([3, 2]) Parameter containing:
tensor([ 0.6820,  0.5795, -0.1028], requires_grad=True)


In [6]:
#Calculate n3, n4, n5 using Pytorch matrix operation
Layer1_1 = tensorX.mm(torch.transpose(W0, 1, 0)) + b0
print(Layer1_1)

tensor([[ 0.1684, -0.9227,  1.5867],
        [-0.2930, -1.8529,  2.7061],
        [-3.6708, -5.8621,  8.2408]], grad_fn=<AddBackward0>)


In [7]:
#Verify
Layer1 = MyNet[0](tensorX)  
print(Layer1)

tensor([[ 0.1684, -0.9227,  1.5867],
        [-0.2930, -1.8529,  2.7061],
        [-3.6708, -5.8621,  8.2408]], grad_fn=<AddmmBackward0>)


###Hidden layer 2: n6, n7

In [8]:
#Calculate n6, n7 using PyTorch matrix operation
W1 = MyNet[1].weight
b1 = MyNet[1].bias  
Layer2_1 = Layer1.mm(torch.transpose(W1, 1, 0)) +b1
print(Layer2_1)

tensor([[ 0.0459, -0.0318],
        [-0.1288, -0.1076],
        [-1.3198, -1.1685]], grad_fn=<AddBackward0>)


In [9]:
#verify 
Layer2 = MyNet[1](Layer1)
print(Layer2)

tensor([[ 0.0459, -0.0318],
        [-0.1288, -0.1076],
        [-1.3198, -1.1685]], grad_fn=<AddmmBackward0>)


###Output layer

In [10]:
#Calculate y by matrix operation
W2 = MyNet[2].weight
b2 = MyNet[2].bias  
tensorY_1 = Layer2.mm(torch.transpose(W2, 1, 0)) +b2
print(tensorY_1)

tensor([[ 0.1322],
        [ 0.0041],
        [-0.9261]], grad_fn=<AddBackward0>)


In [11]:
#verify 
tensorY= MyNet[2](Layer2)
print(tensorY)

tensor([[ 0.1322],
        [ 0.0041],
        [-0.9261]], grad_fn=<AddmmBackward0>)


### y=NN(x) in one step

In [12]:
#Directly calculate y
tensorY= MyNet(tensorX)
print(tensorY)

tensor([[ 0.1322],
        [ 0.0041],
        [-0.9261]], grad_fn=<AddmmBackward0>)
