<a href="https://colab.research.google.com/github/TienLungSun/PyTorch-deep-learning/blob/main/1.3%20MLP%20backward%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
MyNet = nn.Sequential(
  nn.Linear(2, 3),
  nn.Linear(3, 2),
  nn.Linear(2, 1)
)
print(MyNet)

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [3]:
loss_func = torch.nn.MSELoss()

In [4]:
lstX = [[1, 2], [2, 3], [10, 5]]
lstY = [[7], [12], [40]]  # y=3x1+2x2
tensorX = torch.FloatTensor(lstX)
tensorY = torch.FloatTensor(lstY)

tensorY_hat= MyNet(tensorX)
print(tensorY, '\n', tensorY_hat)

tensor([[ 7.],
        [12.],
        [40.]]) 
 tensor([[ 0.2441],
        [ 0.0221],
        [-1.1948]], grad_fn=<AddmmBackward0>)


In [5]:
loss = loss_func(tensorY , tensorY_hat)
print(loss)

tensor(628.7084, grad_fn=<MseLossBackward0>)


In [6]:
for name, param in MyNet.named_parameters():
    if param.requires_grad:
        print(name, '\n', param.data, '\n', param.grad)

0.weight 
 tensor([[-0.2506, -0.5361],
        [ 0.1660, -0.5131],
        [-0.3070, -0.2919]]) 
 None
0.bias 
 tensor([-0.2662,  0.3062,  0.1193]) 
 None
1.weight 
 tensor([[-0.3080, -0.1521,  0.4635],
        [-0.3924, -0.2087, -0.3637]]) 
 None
1.bias 
 tensor([-0.1657, -0.0058]) 
 None
2.weight 
 tensor([[ 0.6691, -0.3901]]) 
 None
2.bias 
 tensor([0.6058]) 
 None


In [7]:
MyNet.zero_grad()
loss.backward()

In [8]:
for name, param in MyNet.named_parameters():
    if param.requires_grad:
        print(name, '\n', param.data, '\n', param.grad)

0.weight 
 tensor([[-0.2506, -0.5361],
        [ 0.1660, -0.5131],
        [-0.3070, -0.2919]]) 
 tensor([[  15.6560,    9.0337],
        [   6.0021,    3.4633],
        [-133.3875,  -76.9660]])
0.bias 
 tensor([-0.2662,  0.3062,  0.1193]) 
 tensor([  2.1196,   0.8126, -18.0584])
1.weight 
 tensor([[-0.3080, -0.1521,  0.4635],
        [-0.3924, -0.2087, -0.3637]]) 
 tensor([[117.6885,  17.5010,  90.6973],
        [-68.6092, -10.2026, -52.8741]])
1.bias 
 tensor([-0.1657, -0.0058]) 
 tensor([-26.7334,  15.5849])
2.weight 
 tensor([[ 0.6691, -0.3901]]) 
 tensor([[  11.2891, -123.5339]])
2.bias 
 tensor([0.6058]) 
 tensor([-39.9524])


In [9]:
learning_rate=0.005
for name, param in MyNet.named_parameters():
    if param.requires_grad:
      param = param - learning_rate*param.grad
      
      nameLst = name.split(".")  #"0.weight" -> ['0', 'weight']
      layerNo = int(nameLst[0])
      s = nameLst[1]
      #update weight and bias
      if(s=="weight"):
        MyNet[layerNo].weight = torch.nn.parameter.Parameter(param)
      elif(s=="bias"):
        MyNet[layerNo].bias = torch.nn.parameter.Parameter(param)
      else:
        print("wrong label")

In [10]:
tensorY_hat= MyNet(tensorX)
print(tensorY)
loss = loss_func(tensorY , tensorY_hat)
print(loss)

tensor([[ 7.],
        [12.],
        [40.]])
tensor(459.2752, grad_fn=<MseLossBackward0>)
